export const regionKeys = {
    uz: [
      ['Toshkent shahar', 'toshkent shahar'],
      ['Toshkent viloyati', 'toshkent viloyat'],
      ['Samarqand', 'samarqand'],
      ['Buxoro', 'buxoro'],
      ['Andijon', 'andijon'],
      ["Farg'ona", 'fargona'],
      ['Namangan', 'namangan'],
      ['Qashqadaryo', 'qashqadaryo'],
      ['Jizzax', 'jizzax'],
      ['Sirdaryo', 'sirdaryo'],
      ['Xorazm', 'xorazm'],
      ['Navoiy', 'navoiy'],
      ['Surxondaryo', 'surxondaryo'],
      ["Qoraqalpog'iston", 'qoraqalpogiston'],
    ],
    ru: [
      ['Город Ташкент', 'toshkent shahar'],
      ['Ташкентская область', 'toshkent viloyat'],
      ['Самарканд', 'samarqand'],
      ['Бухара', 'buxoro'],
      ['Андижан', 'andijon'],
      ['Фергана', 'fargona'],
      ['Наманган', 'namangan'],
      ['Кашкадарья', 'qashqadaryo'],
      ['Джизак', 'jizzax'],
      ['Сырдарья', 'sirdaryo'],
      ['Хорезм', 'xorazm'],
      ['Навои', 'navoiy'],
      ['Сурхандарья', 'surxondaryo'],
      ['Каракалпакстан', 'qoraqalpogiston'],
    ],
  };
  
  export const tashkentCitysKeys = {
    uz: [
      ['Bektemir tumani', 'bektemir'],
      ['Chilonzor tumani', 'chilonzor'],
      ['Mirobod tumani', 'mirobod'],
      ['Mirzo Ulugbek tumani', 'mirzo ulugbek'],
      ['Olmozor tumani', 'olmazor'],
      ['Sergeli tumani', 'sergeli'],
      ['Shayhontohur tumani', 'shayhontohur'],
      ['Uchtepa tumani', 'uchtepa'],
      ['Yakkasaroy tumani', 'yakkasaroy'],
      ['Yashnaobod tumani', 'yashnaobod'],
      ['Yangihayot tumani', 'yangihayot'],
      ['Yunusobod tumani', 'yunusobod'],
    ],
    ru: [
      ['Бектемирский район', 'bektemir'],
      ['Чиланзарский район', 'chilonzor'],
      ['Мирободский район', 'mirobod'],
      ['Мирзо Улугбекский район', 'mirzo ulugbek'],
      ['Олмазорский район', 'olmazor'],
      ['Сергелийский район', 'sergeli'],
      ['Шайхантахурский район', 'shayhontohur'],
      ['Учтепинский район', 'uchtepa'],
      ['Яккасарайский район', 'yakkasaroy'],
      ['Яшнободский район', 'yashnaobod'],
      ['Янгиҳайот район', 'yangihayot'],
      ['Юнусабадский район', 'yunusobod'],
    ],
    en: [
      ['Bektemir district', 'bektemir'],
      ['Chilonzor district', 'chilonzor'],
      ['Mirobod district', 'mirobod'],
      ['Mirzo Ulugbek district', 'mirzo ulugbek'],
      ['Olmazor district', 'olmazor'],
      ['Sergeli district', 'sergeli'],
      ['Shayhontohur district', 'shayhontohur'],
      ['Uchtepa district', 'uchtepa'],
      ['Yakkasaroy district', 'yakkasaroy'],
      ['Yashnaobod district', 'yashnaobod'],
      ['Yangihayot district', 'yangihayot'],
      ['Yunusobod district', 'yunusobod'],
    ],
  };
  
  export const tashkentRegionCitysKeys = {
    uz: [
      ['Bekobod tumani', 'bekobod'],
      ['Boʻka tumani', 'boka'],
      ['Boʻstonliq tumani', 'bostonliq'],
      ['Chinoz tumani', 'chinoz'],
      ['Ohangaron tumani', 'ohangaron'],
      ['Oqqoʻrgʻon tumani', 'oqqorgon'],
      ['Oʻrta Chirchiq tumani', 'ortachirchiq'],
      ['Parkent tumani', 'parkent'],
      ['Piskent tumani', 'piskent'],
      ['Qibray tumani', 'qibray'],
      ['Quyi Chirchiq tumani', 'quyichirchiq'],
      ['Toshkent tumani', 'toshkent'],
      ['Yangiyoʻl tumani', 'yangiyol'],
      ['Yuqori Chirchiq tumani', 'yuqorichirchiq'],
      ['Zangiota tumani', 'zangiota'],
    ],
    ru: [
      ['Бекабадский район', 'bekobod'],
      ['Бука', 'boka'],
      ['Бостонликский район', 'bostonliq'],
      ['Чинозский район', 'chinoz'],
      ['Оҳангаронский район', 'ohangaron'],
      ['Оққўрғонский район', 'oqqorgon'],
      ['Орта Чирчиқский район', 'ortachirchiq'],
      ['Паркентский район', 'parkent'],
      ['Пискентский район', 'piskent'],
      ['Қибрайский район', 'qibray'],
      ['Қуйи Чирчиқский район', 'quyichirchiq'],
      ['Тошкентский район', 'toshkent'],
      ['Янгиёлский район', 'yangiyol'],
      ['Юқори Чирчиқский район', 'yuqorichirchiq'],
      ['Зангиотинский район', 'zangiota'],
    ],
  };
  
  export const ferganaCitysKeys = {
    uz: [
      ['Bagʻdod tumani', 'bogdod'],
      ['Beshariq tumani', 'beshariq'],
      ['Buvayda tumani', 'buvayda'],
      ['Dangʻara tumani', 'dangara'],
      ['Fargʻona tumani', 'fargona'],
      ['Furqat tumani', 'furqat'],
      ['Oltiariq tumani', 'oltiariq'],
      ['Oyim tumani', 'oyim'],
      ['Oʻzbekiston tumani', 'ozbekiston'],
      ['Qoʻshtepa tumani', 'qoshtepa'],
      ['Quva tumani', 'quva'],
      ['Rishton tumani', 'rishton'],
      ['Soʻx tumani', 'sox'],
      ['Toshloq tumani', 'toshloq'],
      ['Uchkoʻprik tumani', 'uchkoprik'],
      ['Voroshilov tumani', 'voroshilov'],
      ['Yozyovon tumani', 'yozyovon'],
    ],
    ru: [
      ['Багдодский район', 'bogdod'],
      ['Бешарыкский район', 'beshariq'],
      ['Бувайдо', 'buvayda'],
      ['Дангаринский район', 'dangara'],
      ['Ферганский район', 'fargona'],
      ['Фуркатский район', 'furqat'],
      ['Олтарикский район', 'oltiariq'],
      ['Ойим', 'oyim'],
      ['Узбекистанский район', 'ozbekiston'],
      ['Қўштепа', 'qoshtepa'],
      ['Қува', 'quva'],
      ['Риштонский район', 'rishton'],
      ['Сох', 'sox'],
      ['Тошлок', 'toshloq'],
      ['Учкўприк', 'uchkoprik'],
      ['Ворошиловский район', 'voroshilov'],
      ['Ёзёвон', 'yozyovon'],
    ],
  };
  
  export const samarkandCityKeys = {
    uz: [
      ['Samarqand tumani', 'samarqand'],
      ['Ishtixon tumani', 'ishtixon'],
      ['Jomboy tumani', 'jomboy'],
      ['Urgut tumani', 'urgut'],
      ['Kattakurgan tumani', 'kattakurgan'],
      ['Pastdargom tumani', 'pastdargom'],
      ['Narpay tumani', 'narpay'],
      ['Payariq tumani', 'payariq'],
      ['Bulungur tumani', 'bulungur'],
      ['Oqdaryo tumani', 'oqdaryo'],
      ['Toyloq tumani', 'toyloq'],
      ['Qo‘shrabot tumani', 'qoshrabot'],
      ['Nurobod tumani', 'nurobod'],
      ['Paxtachi tumani', 'paxtachi'],
      ['Oqdaryo tumani', 'oqdaryo_tumani'],
    ],
    ru: [
      ['Самарканд округ', 'samarqand'],
      ['Иштыхан округ', 'ishtixon'],
      ['Джамбай округ', 'jomboy'],
      ['Ургут округ', 'urgut'],
      ['Каттакурган округ', 'kattakurgan'],
      ['Пастдаргом округ', 'pastdargom'],
      ['Нарпай округ', 'narpay'],
      ['Паярик округ', 'payariq'],
      ['Булунгур округ', 'bulungur'],
      ['Акдарья округ', 'oqdaryo'],
      ['Тойлак округ', 'toyloq'],
      ['Кушработ округ', 'qoshrabot'],
      ['Нурабад округ', 'nurobod'],
      ['Пахтачи округ', 'paxtachi'],
      ['Акдарья округ', 'oqdaryo_tumani'],
    ],
  };
  
  export const bukharaCityKeys = {
    uz: [
      ['Buxoro tumani', 'bukhara'],
      ['G‘ijduvon tumani', 'gijduvon'],
      ['Kogon tumani', 'kogon'],
      ['Olot tumani', 'olot'],
      ['Jondor tumani', 'jondor'],
      ['Kogon tumani', 'kogon'],
      ['Peshku tumani', 'peshku'],
      ['Qorako‘l tumani', 'qorakol'],
      ['Qorovulbozor tumani', 'qorovulbozor'],
      ['Romitan tumani', 'romitan'],
      ['Shofirkon tumani', 'shofirkon'],
      ['Vobkent tumani', 'vobkent'],
    ],
    ru: [
      ['Бухара округ', 'bukhara'],
      ['Гиждуван округ', 'gijduvon'],
      ['Когон округ', 'kogon'],
      ['Олот округ', 'olot'],
      ['Джондор округ', 'jondor'],
      ['Когон округ', 'kogon'],
      ['Пешку округ', 'peshku'],
      ['Каракуль округ', 'qorakol'],
      ['Караулбазар округ', 'qorovulbozor'],
      ['Ромитан округ', 'romitan'],
      ['Шофиркон округ', 'shofirkon'],
      ['Вабкент округ', 'vobkent'],
    ],
  };
  
  export const namanganCityKeys = {
    uz: [
      ['Chortoq tumani', 'chortoq'],
      ['Chust tumani', 'chust'],
      ['Kosonsoy tumani', 'kosonsoy'],
      ['Mingbuloq tumani', 'mingbuloq'],
      ['Namangan tumani', 'namangan'],
      [' Norin tumani', 'norin'],
      ['Pop tumani', 'pop'],
      ['Toʻraqoʻrgʻon tumani', 'toraqorgon'],
      ['Uchqoʻrgʻon tumani', 'uchqorgon'],
      ['Uychi tumani', 'uychi'],
      ['Yangiqoʻrgʻon tumani', 'yangiqorgon'],
      ['Yangi Namangan tumani', 'yanginamangan'],
    ],
    ru: [
      ['Чартакский район', 'chortoq'],
      ['Чустский район', 'chust'],
      ['Косонсойский район', 'kosonsoy'],
      ['Мингбулакский район', 'mingbuloq'],
      ['Наманганский район', 'namangan'],
      ['Нарынский район', 'norin'],
      ['Попский район', 'pop'],
      ['Туракурганский район', 'toraqorgon'],
      ['Учкурганский район', 'uchqorgon'],
      ['Уйчинский район', 'uychi'],
      ['Янгикурганский район', 'yangiqorgon'],
      ['Янги Наманганский район', 'yanginamangan'],
    ],
  };
  
  export const andijanCityKeys = {
    uz: [
      ['Andijon tumani', 'andijon'],
      ['Asaka tumani', 'asaka'],
      ['Baliqchi tumani', 'baliqchi'],
      ["Bo'ston tumani", 'boz'],
      ['Buloqboshi tumani', 'buloqboshi'],
      ['Izboskan tumani', 'izboskan'],
      ['Jalaquduq tumani', 'jalaquduq'],
      ['Xo‘jaobod tumani', 'xojaobod'],
      ['Qo‘rg‘ontepa tumani', 'qorgontepa'],
      ['Marhamat tumani', 'marhamat'],
      ['Oltinko‘l tumani', 'oltinkol'],
      ['Paxtaobod tumani', 'paxtaobod'],
      ['Shahrixon tumani', 'shahrixon'],
      ['Ulug‘nor tumani', 'ulugnor'],
    ],
    ru: [
      ['Андижанский район', 'andijon'],
      ['Асакинский район', 'asaka'],
      ['Балыкчинский район', 'baliqchi'],
      ['Бостонский район', 'boz'],
      ['Булокбошинский район', 'buloqboshi'],
      ['Избосканский район', 'izboskan'],
      ['Джалакудукский район', 'jalaquduq'],
      ['Мархаматский район', 'marhamat'],
      ['Алтынкульский район', 'oltinkol'],
      ['Пахтаабадский район', 'paxtaobod'],
      ['Кургантепинский район', 'qorgontepa'],
      ['Шахриханский район', 'shahrixon'],
      ['Улугнорский район', 'ulugnor'],
      ['Ходжаабад район', 'xojaobod'],
    ],
  };
  
  export const qashqadaryaCityKeys = {
    uz: [
      ['Bahoriston tumani', 'bahoriston'],
      ['Chiroqchi tumani', 'chiroqchi'],
      ['Dehqonobod tumani', 'dehqonobod'],
      ['Gʻuzor tumani', 'guzor'],
      ['Kasbi tumani', 'kasbi'],
      ['Kitob tumani', 'kitob'],
      ['Koson tumani', 'koson'],
      ['Koʻkdala tumani', 'kokdala'],
      ['Mirishkor tumani', 'mirishkor'],
      ['Muborak tumani', 'muborak'],
      ['Nishon tumani', 'nishon'],
      ['Qamashi tumani', 'qamashi'],
      ['Qarshi tumani', 'qarshi'],
      ['Shahrisabz tumani', 'shahrisabz'],
      ['Yakkabogʻ tumani', 'yakkabog'],
    ],
    ru: [
      ['Бахористонский район', 'bahoriston'],
      ['Чиракчинский район', 'chiroqchi'],
      ['Дехканабадский район', 'dehqonobod'],
      ['Гузарский район', 'guzor'],
      ['Касбинский район', 'kasbi'],
      ['Китабский район', 'kitob'],
      ['Касанский район', 'koson'],
      ['Кукдалинский район', 'kokdala'],
      ['Миришкорский район', 'mirishkor'],
      ['Мубарекский район', 'muborak'],
      ['Нишанский район', 'nishon'],
      ['Камашинский район', 'qamashi'],
      ['Каршинский район', 'qarshi'],
      ['Шахрисабзский район', 'shahrisabz'],
      ['Яккабогский район', 'yakkabog'],
    ],
  };
  
  export const jizzaxCityKeys = {
    uz: [
      ['Jizzax tumani', 'jizzax'],
      ['Arnasoy tumani', 'arnasoy'],
      ['Baxmal tumani', 'baxmal'],
      ['Do‘stlik tumani', 'dostlik'],
      ['Forish tumani', 'forish'],
      ['G‘allaorol tumani', 'gallaorol'],
      ['Sharof Rashidov tumani', 'sharof_rashidov'],
      ['Mirzacho‘l tumani', 'mirzachol'],
      ['Paxtakor tumani', 'paxtakor'],
      ['Yangiobod tumani', 'yangiobod'],
      ['Zafarobod tumani', 'zafarobod'],
      ['Zarbdor tumani', 'zarbdor'],
    ],
    ru: [
      ['Джизакский район', 'jizzax'],
      ['Арнасайский район', 'arnasoy'],
      ['Бахмальский район', 'baxmal'],
      ['Дустликский район', 'dostlik'],
      ['Фаришский район', 'forish'],
      ['Галлааральский район', 'gallaorol'],
      ['Шароф Рашидов район', 'sharof_rashidov'],
      ['Мирзачульский район', 'mirzachol'],
      ['Пахтакорский район', 'paxtakor'],
      ['Янгиабадский район', 'yangiobod'],
      ['Зафарабадский район', 'zafarobod'],
      ['Зарбдорский район', 'zarbdor'],
    ],
  };
  
  export const sirdaryoCityKeys = {
    uz: [
      ['Sirdaryo tumani', 'sirdaryo'],
      ['Boyovut tumani', 'boyovut'],
      ['Guliston tumani', 'guliston'],
      ['Mirzaobod tumani', 'mirzaobod'],
      ['Oqoltin tumani', 'oqoltin'],
      ['Sayxunobod tumani', 'sayxunobod'],
      ['Sardoba tumani', 'sardoba'],
      ['Xovos tumani', 'xovos'],
      ['Yangiyer tumani', 'yangiyer'],
    ],
    ru: [
      ['Сырдарьинский район', 'sirdaryo'],
      ['Баяутский район', 'boyovut'],
      ['Гулистанский район', 'guliston'],
      ['Мирзаабадский район', 'mirzaobod'],
      ['Акалтынский район', 'oqoltin'],
      ['Сайхунабадский район', 'sayxunobod'],
      ['Сардобинский район', 'sardoba'],
      ['Хавасский район', 'xovos'],
      ['Янгиерский район', 'yangiyer'],
    ],
  };
  
  export const xorazmCityKeys = {
    uz: [
      ['Urganch tumani', 'urganch'],
      ['Bogʻot tumani', 'bogot'],
      ['Gurlan tumani', 'gurlan'],
      ['Xiva tumani', 'xiva'],
      ['Xonqa tumani', 'xonqa'],
      ['Hazorasp tumani', 'hazorasp'],
      ['Shovot tumani', 'shovot'],
      ['Yangiariq tumani', 'yangiariq'],
      ['Yangibozor tumani', 'yangibozor'],
      ['Qoʻshkoʻpir tumani', 'qoshkoprik'],
      ['Tuproqqalʼa tumani', 'tuproqqala'],
    ],
    ru: [
      ['Ургенчский район', 'urganch'],
      ['Багатский район', 'bogot'],
      ['Гурланский район', 'gurlan'],
      ['Хивинский район', 'xiva'],
      ['Ханкинский район', 'xonqa'],
      ['Хазараспский район', 'hazorasp'],
      ['Шаватский район', 'shovot'],
      ['Янгиарикский район', 'yangiariq'],
      ['Янгибазарский район', 'yangibozor'],
      ['Кошкупырский район', 'qoshkoprik'],
      ['Тупраккалинский район', 'tuproqqala'],
    ],
  };
  
  export const surxandaryaCityKeys = {
    uz: [
      ['Angor tumani', 'angor'],
      ['Bandixon tumani', 'bandixon'],
      ['Boysun tumani', 'boysun'],
      ['Denov tumani', 'denov'],
      ['Jarqoʻrgʻon tumani', 'jarqorgon'],
      ['Qiziriq tumani', 'qiziriq'],
      ['Qumqoʻrgʻon tumani', 'qumqoron'],
      ['Muzrabod tumani', 'muzrabod'],
      ['Oltinsoy tumani', 'oltinsoy'],
      ['Sariosiyo tumani', 'sariosiyo'],
      ['Sherobod tumani', 'sherobod'],
      ['Shoʻrchi tumani', 'shorchi'],
      ['Termiz tumani', 'termiz'],
      ['Uzun tumani', 'uzun'],
    ],
    ru: [
      ['Ангорский район', 'angor'],
      ['Бандиханский район', 'bandixon'],
      ['Байсунский район', 'boysun'],
      ['Денауский район', 'denov'],
      ['Джаркурганский район', 'jarqorgon'],
      ['Кызырыкский район', 'qiziriq'],
      ['Кумкурганский район', 'qumqoron'],
      ['Музрабадский район', 'muzrabod'],
      ['Алтынсайский район', 'oltinsoy'],
      ['Сариасийский район', 'sariosiyo'],
      ['Шерабадский район', 'sherobod'],
      ['Шурчинский район', 'shorchi'],
      ['Термезский район', 'termiz'],
      ['Узунский район', 'uzun'],
    ],
  };
  
  export const karakalpakstanCityKeys = {
    uz: [
      ['Amudaryo tumani', 'amudaryo'],
      ['Beruniy tumani', 'beruniy'],
      ['Chimboy tumani', 'chimboy'],
      ['Ellikqala tumani', 'ellikqala'],
      ['Kegeyli tumani', 'kegeyli'],
      ['Moʻynoq tumani', 'moynoq'],
      ['Nukus tumani', 'nukus'],
      ['Qanlikoʻl tumani', 'qanlikol'],
      ['Qoʻngʻirot tumani', 'qongirot'],
      ['Qoraoʻzak tumani', 'qoraozak'],
      ['Shumanay tumani', 'shumanay'],
      ['Taxtakoʻpir tumani', 'taxtakopir'],
      ['Toʻrtkoʻl tumani', 'tortkol'],
      ['Xoʻjayli tumani', 'xojayli'],
    ],
    ru: [
      ['Амударьинский район', 'amudaryo'],
      ['Беруниский район', 'beruniy'],
      ['Чимбайский район', 'chimboy'],
      ['Элликкалинский район', 'ellikqala'],
      ['Кегейлийский район', 'kegeyli'],
      ['Муйнакский район', 'moynoq'],
      ['Нукусский район', 'nukus'],
      ['Канлыкульский район', 'qanlikol'],
      ['Кунградский район', 'qongirot'],
      ['Караузякский район', 'qoraozak'],
      ['Шуманайский район', 'shumanay'],
      ['Тахтакупырский район', 'taxtakopir'],
      ['Турткульский район', 'tortkol'],
      ['Ходжейлийский район', 'xojayli'],
    ],
  };
  
  export const navoiCityKeys = {
    uz: [
      ['Konimex tumani', 'konimex'],
      ['Karmana tumani', 'karmana'],
      ['Qiziltepa tumani', 'qiziltepa'],
      ['Xatirchi tumani', 'xatirchi'],
      ['Navbahor tumani', 'navbahor'],
      ['Nurota tumani', 'nurota'],
      ['Tomdi tumani', 'tomdi'],
      ['Uchquduq tumani', 'uchquduq'],
    ],
    ru: [
      ['Конимехский район', 'konimex'],
      ['Карманинский район', 'karmana'],
      ['Кызылтепинский район', 'qiziltepa'],
      ['Хатырчинский район', 'xatirchi'],
      ['Навбахорский район', 'navbahor'],
      ['Нуротинский район', 'nurota'],
      ['Томдинский район', 'tomdi'],
      ['Учкудукский район', 'uchquduq'],
    ],
  };
  